version: "3"
services:
  powerdns:
    image: powerdns/pdns-auth-47
    networks:
      - backend
    volumes:
      - ./.docker/pdns:/etc/powerdns/pdns.d
    ports:
      - 8081:8081
networks:
  backend: {}
